### ISSUE TITLE
Stop transitions which happen on page load

### ISSUE THREAD

**Issue by MTM828** [MTM828/MTM828.github.io#2]
Transitions are happening when the page loads, this is because JS saves dark mode thus it automatically switches. I need to fix this.

**Comment by MTM828** [comment]
It looks like setting transitions to 0s and resetting them to their defaults also didn't work, I'll see why.

**Comment by MTM828** [comment]
I HATE YOU JS!!!

**Comment by elif-bunny** [comment]
Created pull request. Please check [here](https://github.com/MTM828/MTM828.github.io/pull/4)

**Comment by MTM828** [comment]
@elif-bunny Kudos mate, really helped!
