### ISSUE TITLE
There Is  Bug In Your code

### ISSUE THREAD

**Issue by javascript-programmer** [MTM828/mtm828.github.io#5]
You have a bug in your code if you go to your website and scroll down you will find <p id=sig ><p>
I know how to fix it you have to do <p>Id=sig<p> also the P stands for pharaghraph so you will id=sig instead of <p id=sig ><p>

**Comment by javascript-programmer** [comment]
umm now its  gone

**Comment by MTM828** [comment]
I know, it's something I've been working on.
